// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn2uZruyWcCEnpOiEOORVIjZN_WnL_fYI',
    appId: '1:888973432929:web:1775ba941c108d406f3220',
    messagingSenderId: '888973432929',
    projectId: 'messageme-589e0',
    authDomain: 'messageme-589e0.firebaseapp.com',
    storageBucket: 'messageme-589e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd-Gzet2DTLcxpgnQ_EfmDbKj2geF-voc',
    appId: '1:888973432929:android:89b643d34561e4756f3220',
    messagingSenderId: '888973432929',
    projectId: 'messageme-589e0',
    storageBucket: 'messageme-589e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMzjxiNlEGsn6AOWF8YLKIAPuOGivO6Ew',
    appId: '1:888973432929:ios:618fd9a0aa6a3aad6f3220',
    messagingSenderId: '888973432929',
    projectId: 'messageme-589e0',
    storageBucket: 'messageme-589e0.firebasestorage.app',
    iosClientId: '888973432929-s5548tpmi3t9hnn2ulgf6h3vsjvarsvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.instegramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMzjxiNlEGsn6AOWF8YLKIAPuOGivO6Ew',
    appId: '1:888973432929:ios:618fd9a0aa6a3aad6f3220',
    messagingSenderId: '888973432929',
    projectId: 'messageme-589e0',
    storageBucket: 'messageme-589e0.firebasestorage.app',
    iosClientId: '888973432929-s5548tpmi3t9hnn2ulgf6h3vsjvarsvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.instegramApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn2uZruyWcCEnpOiEOORVIjZN_WnL_fYI',
    appId: '1:888973432929:web:ffdd5a9b95a265426f3220',
    messagingSenderId: '888973432929',
    projectId: 'messageme-589e0',
    authDomain: 'messageme-589e0.firebaseapp.com',
    storageBucket: 'messageme-589e0.firebasestorage.app',
  );
}
