// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEiZWIqiCvKRPU9oGUbiZalV8s58A0Trw',
    appId: '1:506753532577:web:efadabbffa7cdf3acc66e0',
    messagingSenderId: '506753532577',
    projectId: 'inestagram-clone',
    authDomain: 'inestagram-clone.firebaseapp.com',
    storageBucket: 'inestagram-clone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa-ODECuSJrlYVDY745JEPDvkLlcJ8ELM',
    appId: '1:506753532577:android:cda9fe7d72f02747cc66e0',
    messagingSenderId: '506753532577',
    projectId: 'inestagram-clone',
    storageBucket: 'inestagram-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyFASAdH5GV71z-iVOUSUymiCngbBpWyg',
    appId: '1:506753532577:ios:5702384d73a64358cc66e0',
    messagingSenderId: '506753532577',
    projectId: 'inestagram-clone',
    storageBucket: 'inestagram-clone.firebasestorage.app',
    iosBundleId: 'com.example.instegramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyFASAdH5GV71z-iVOUSUymiCngbBpWyg',
    appId: '1:506753532577:ios:5702384d73a64358cc66e0',
    messagingSenderId: '506753532577',
    projectId: 'inestagram-clone',
    storageBucket: 'inestagram-clone.firebasestorage.app',
    iosBundleId: 'com.example.instegramApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEiZWIqiCvKRPU9oGUbiZalV8s58A0Trw',
    appId: '1:506753532577:web:77a859b0fccd2ab2cc66e0',
    messagingSenderId: '506753532577',
    projectId: 'inestagram-clone',
    authDomain: 'inestagram-clone.firebaseapp.com',
    storageBucket: 'inestagram-clone.firebasestorage.app',
  );

}